#!/usr/bin/env python3

from zipfile import ZIP_DEFLATED, ZipFile

folder = 'src/it/setup-dependencies'


def create(name, extension='jar'):
    with ZipFile(f'{folder}/{name}.{extension}', 'w', ZIP_DEFLATED) as zipf:
        zipf.writestr(name, name)


create('leaf-1.0')
create('another-leaf-1.0')
create('a-third-leaf-1.0')
create('a-classified-leaf-1.0-classy')
create('with-dependency-1.0')
create('a-war-1.0', 'war')
