#!/usr/bin/env bash
set -eu -o pipefail

docker run --rm\
 -v "${PWD}":/local\
 vandmo/google-java-format@sha256:a2a2741e6976ac565f3406206382070ba645d5de4b8d5afbe24ef6f717eac0fc\
 find /local/ -name '*.java' -exec google-java-format -i {} \;
