#!/usr/bin/env bash
set -eu -o pipefail

docker run --rm\
 -v "${PWD}":/local\
 vandmo/google-java-format@sha256:56d5dc04548f34d455045ef5fbf469d46e24cbc8c5e061320d48bf7fb79513fc\
 find /local/ -name '*.java' -exec google-java-format -i {} \;
