#!/usr/bin/env bash
set -eu -o pipefail

./mvnw clean install post-site --activate-profiles its,analyze
./mvnw com.github.spotbugs:spotbugs-maven-plugin:4.8.6.6:spotbugs com.github.spotbugs:spotbugs-maven-plugin:4.8.6.6:check --define spotbugs.excludeFilterFile=spotbugs-suppressions.xml
