#!/usr/bin/env bash
set -eu -o pipefail

mvn clean install --activate-profiles its,analyze
mvn com.github.spotbugs:spotbugs-maven-plugin:4.4.2:spotbugs com.github.spotbugs:spotbugs-maven-plugin:4.4.2:check --define spotbugs.excludeFilterFile=spotbugs-suppressions.xml
