#!/usr/bin/env python3

import base64
import hashlib
import os

folder = 'src/it/setup/dependencies'
for filename in os.listdir(folder):
    if filename.endswith('.jar') or filename.endswith('.war'):
        sha512 = hashlib.sha512()
        fullname = os.path.join(folder, filename)
        with open(fullname, 'rb') as f:
            sha512.update(f.read())
            b64 = base64.b64encode(sha512.digest()).decode('utf-8')
            print(f'{fullname}: sha512:{b64}')
