name: Tests Maven 4.0.0-rc-4

on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Tests Maven 4.0.0-rc-4

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          cache: maven
          distribution: zulu
          java-version: 21
      # Done this way due to defects in maven 4.0.0-beta-5 to 4.0.0.rc-4 that fail to execute maven (associated fix in maven wrapper scripts for maven 4 main class)
      - name: Set Maven Wrapper version
        run: sed -i "s|^distributionUrl=.*|distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/4.0.0-rc-4/apache-maven-4.0.0-rc-4-bin.zip|" .mvn/wrapper/maven-wrapper.properties
      - name: Test with Maven
        run: ./mvnw --batch-mode --show-version verify --activate-profiles analyze,its -Dmaven.min-version=4.0.0-rc-4 -Dmaven=4.0.0-rc-4 --no-transfer-progress
